"""empty message

Revision ID: 59a04688e003
Revises: None
Create Date: 2015-12-20 00:39:43.549166

"""

# revision identifiers, used by Alembic.
revision = '59a04688e003'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('work',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('importance', sa.Enum('so-so', 'important', 'very important', name='importance_type'), nullable=True),
    sa.Column('done', sa.Boolean(), nullable=True),
    sa.Column('expired', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('work')
    ### end Alembic commands ###
